// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjQtsGeMtKPx74eh0kUl0OL0QoMBp-4AI',
    appId: '1:49621979359:web:44c0fe4e77e9497df2596a',
    messagingSenderId: '49621979359',
    projectId: 'jerusalemchess-ae755',
    authDomain: 'jerusalemchess-ae755.firebaseapp.com',
    storageBucket: 'jerusalemchess-ae755.appspot.com',
    measurementId: 'G-DZ4WXQCCFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChSOcX4wECFRW0Uxom91xRM1hKtryhK-g',
    appId: '1:49621979359:android:a23dfed85e285280f2596a',
    messagingSenderId: '49621979359',
    projectId: 'jerusalemchess-ae755',
    storageBucket: 'jerusalemchess-ae755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgXUZmqWNrE3_ubWpQjFdrYtbW1kkPlGY',
    appId: '1:49621979359:ios:33c77cf271f064f3f2596a',
    messagingSenderId: '49621979359',
    projectId: 'jerusalemchess-ae755',
    storageBucket: 'jerusalemchess-ae755.appspot.com',
    iosBundleId: 'com.example.flutterChess1',
  );
}
